# Generated by Django 4.2.4 on 2023-08-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('instagram', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('twitter', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('website', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('slack', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('reddit', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('behance', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('dribbble', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('fiverr', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('upwork', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('freelancer', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Links', to='authent.user')),
            ],
        ),
    ]
