# Generated by Django 4.2.2 on 2023-08-28 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='behance',
            new_name='Behance',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='dribbble',
            new_name='Dribbble',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='facebook',
            new_name='Facebook',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='fiverr',
            new_name='Fiverr',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='freelancer',
            new_name='Freelancer',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='instagram',
            new_name='Instagram',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='linkedin',
            new_name='Linkedin',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='reddit',
            new_name='Reddit',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='slack',
            new_name='Slack',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='twitter',
            new_name='Twitter',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='upwork',
            new_name='Upwork',
        ),
        migrations.RenameField(
            model_name='links',
            old_name='website',
            new_name='Website',
        ),
    ]
