# Generated by Django 4.2.4 on 2023-08-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='behance',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='dribbble',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='fiverr',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='freelancer',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='linkedin',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='reddit',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='slack',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='twitter',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='upwork',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='links',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
